# Uncomment the next line to define a global platform for your project
# platform :ios, '11.1'

target 'dynamic_forms' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Eureka'
  # Pods for dynamic_forms

  target 'dynamic_formsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'dynamic_formsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
